# Generated by Django 6.0.4 on 2026-07-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('new_client', 'Новый клиент'), ('rename_client', 'Переименование клиента'), ('add_address', 'Добавить адрес существующему клиенту'), ('change_payment', 'Изменение формы оплаты')], default='new_client', max_length=255)),
                ('payment_type', models.CharField(choices=[('fact', 'Факт'), ('cashless', 'Безналичная оплата'), ('delivery_to_delivery', 'От поставки до поставки'), ('prepayment', 'Предоплата')], default='fact', max_length=255)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('needs_review', 'Требует проверки'), ('approved', 'Проверена'), ('exported', 'Выгружена'), ('rejected', 'Отклонена')], default='new', max_length=32, verbose_name='Статус')),
                ('client_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(max_length=9)),
                ('legal_address', models.TextField(max_length=255)),
                ('actual_address', models.TextField(max_length=255)),
                ('delivery_address', models.TextField(max_length=255)),
                ('gps_coordinates', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=255)),
                ('delivery_start_time', models.TimeField()),
                ('delivery_end_time', models.TimeField()),
                ('has_break', models.BooleanField(default=False)),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
