# Generated by Django 6.0.4 on 2026-07-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='geo_check_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='geo_check_status',
            field=models.CharField(choices=[('not_checked', 'Не проверялась'), ('passed', 'Проверка пройдена'), ('failed', 'Ошибка проверки'), ('error', 'Ошибка сервиса')], default='not_checked', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='geo_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
